include:
  - board: seeeduino_xiao_ble
    shield: saurus_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: saurus_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
