include:
  - board: xiao_ble
    shield: saurus_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: saurus_right rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
